app_environments: 
  - name: dev
    fields: 
      - name: short_name
        type: String
        value: dev
      - name: long_name
        type: String
        value: Development
  - name: test
    fields: 
      - name: short_name
        type: String
        value: test
      - name: long_name
        type: String
        value: Test    
