environments: 
  dev:
    short_name: dev
    long_name: Development
    ask_approval: true
    number_bananas: 6
  test:
    short_name: test
    long_name: Test
    ask_approval: true
    number_bananas: 0

