app_environments: 
  - name: dev
    fields: 
      - name: short_name
        type: String
        value: dev
      - name: long_name
        type: String
        value: Development
      - name: ask_approval
        type: Boolean
        value: true
      - name: number_bananas
        type: Int
        value: 6
  - name: test
    fields: 
      - name: short_name
        type: String
        value: test
      - name: long_name
        type: String
        value: Test
      - name: ask_approval
        type: Boolean
        value: false
      - name: number_bananas
        type: Int
        value: 7
  - name: staging
    fields: 
      - name: short_name
        type: String
        value: staging
      - name: long_name
        type: String
        value: Staging
      - name: ask_approval
        type: Boolean
        value: true
      - name: number_bananas
        type: Int
        value: 100
